config/routes.rb
Rails.application.routes.draw do

  namespace :backoffice do
    resources :gyms, except: [:show]
    resources :students, except: [:show]
    resources :roles, except: [:show]
    resources :profiles, except: [:show]
    resources :admins, except: [:show]

    get '/states/:state_id/cities', to: 'cities#cities_of_state'
  end

  devise_for :admins, :skip => [:registrations]
  root 'backoffice/gyms#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/shared_backoffice/_chat.html.erb
<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right" id="cbp-spmenu-s1">
    <h3><span class="pull-left">Chat</span><a href="javascript:void(0);" class="pull-right" id="closeRight"><i class="fa fa-times"></i></a></h3>
    <div class="slimscroll">
        <a href="javascript:void(0);" class="showRight2"><%= image_tag('backoffice/avatar2.png', alt: "") %><span>Sandra smith<small>Hi! How're you?</small></span></a>
        <a href="javascript:void(0);" class="showRight2"><%= image_tag('backoffice/avatar3.png', alt: "") %><span>Amily Lee<small>Hi! How're you?</small></span></a>
        <a href="javascript:void(0);" class="showRight2"><%= image_tag('backoffice/avatar4.png', alt: "") %><span>Christopher Palmer<small>Hi! How're you?</small></span></a>
        <a href="javascript:void(0);" class="showRight2"><%= image_tag('backoffice/avatar5.png', alt: "") %><span>Nick Doe<small>Hi! How're you?</small></span></a>
        <a href="javascript:void(0);" class="showRight2"><%= image_tag('backoffice/avatar2.png', alt: "") %><span>Sandra smith<small>Hi! How're you?</small></span></a>
        <a href="javascript:void(0);" class="showRight2"><%= image_tag('backoffice/avatar3.png', alt: "") %><span>Amily Lee<small>Hi! How're you?</small></span></a>
        <a href="javascript:void(0);" class="showRight2"><%= image_tag('backoffice/avatar4.png', alt: "") %><span>Christopher Palmer<small>Hi! How're you?</small></span></a>
        <a href="javascript:void(0);" class="showRight2"><%= image_tag('backoffice/avatar5.png', alt: "") %><span>Nick Doe<small>Hi! How're you?</small></span></a>
    </div>
</nav>

app/views/layouts/shared_backoffice/_modals.html.erb
<div class="col-md-12">
  <div id="modal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <%= yield :modal_lg_content %>
        </div>
    </div>
  </div>
  <div class="modal fade" id="confirm_delete_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
            <%= yield :modal_confirm_delete %>
          </div>
      </div>
  </div>
</div>

app/views/layouts/shared_backoffice/_navigation.html.erb
<!-- Navbar -->
            <div class="page-sidebar sidebar">
                <div class="page-sidebar-inner slimscroll">
                    <div class="sidebar-header">
                        <div class="sidebar-profile">
                            <a href="javascript:void(0);" id="profile-menu-link">
                                <div class="sidebar-profile-image">
                                    <%= image_tag('backoffice/avatar1.png', class: "img-circle img-responsive", alt: "") %>
                                </div>
                                <div class="sidebar-profile-details">
                                    <span>David Green<br><small>Art Director</small></span>
                                </div>
                            </a>
                        </div>
                    </div>
                    <ul class="menu accordion-menu">

                        <li><a href="index.html" class="waves-effect waves-button"><span class="menu-icon glyphicon glyphicon-home"></span><p>Dashboard</p></a></li>
                        <li><a href="profile.html" class="waves-effect waves-button"><span class="menu-icon glyphicon glyphicon-user"></span><p>Profile</p></a></li>



                        <li class="droplink active open"><a href="#" class="waves-effect waves-button"><span class="menu-icon glyphicon glyphicon-th"></span><p><%= t 'labels.tables' %></p><span class="arrow"></span></a>
                            <ul class="sub-menu">
                                <% if can? :update, Gym %>
                                    <li class="<%= 'active' if params[:controller] == 'backoffice/gyms' %>">
                                        <%= link_to backoffice_gyms_path do %>
                                            <%= Gym.model_name.human %>
                                        <% end %>
                                    </li>
                                <% end %>
                                <% if can? :update, Student %>
                                    <li class="<%= 'active' if params[:controller] == 'backoffice/students' %>">
                                        <%= link_to backoffice_students_path do %>
                                            <%= Student.model_name.human %>
                                        <% end %>
                                    </li>
                                <% end %>
                                <% if can? :update, Admin %>
                                    <li class="<%= 'active' if params[:controller] == 'backoffice/admins' %>">
                                        <%= link_to backoffice_admins_path do %>
                                            <%= Admin.model_name.human %>
                                        <% end %>
                                    </li>
                                <% end %>
                                <% if can? :update, Profile %>
                                    <li class="<%= 'active' if params[:controller] == 'backoffice/profiles' %>">
                                        <%= link_to backoffice_profiles_path do %>
                                            <%= Profile.model_name.human %>
                                        <% end %>
                                    </li>
                                <% end %>
                                <% if can? :update, Role %>
                                    <li class="<%= 'active' if params[:controller] == 'backoffice/roles' %>">
                                        <%= link_to backoffice_roles_path do %>
                                            <%= Role.model_name.human %>
                                        <% end %>
                                    </li>
                                <% end %>
                            </ul>
                        </li>

                    </ul>
                </div><!-- Page Sidebar Inner -->
            </div><!-- Page Sidebar -->

app/views/layouts/shared_backoffice/_profile.html.erb
<div class="menu-wrap">
    <nav class="profile-menu">
        <div class="profile"><%= image_tag('backoffice/avatar1.png', width: "52", alt: "David Green") %><span>David Green</span></div>
        <div class="profile-menu-list">
            <a href="#"><i class="fa fa-star"></i><span>Favorites</span></a>
            <a href="#"><i class="fa fa-bell"></i><span>Alerts</span></a>
            <a href="#"><i class="fa fa-envelope"></i><span>Messages</span></a>
            <a href="#"><i class="fa fa-comment"></i><span>Comments</span></a>
        </div>
    </nav>
    <button class="close-button" id="close-button">Close Menu</button>
</div>

app/views/layouts/shared_backoffice/_quick_navigation.html.erb
<nav class="cd-nav-container" id="cd-nav">
    <header>
        <h3>Navigation</h3>
        <a href="#0" class="cd-close-nav">Close</a>
    </header>
    <ul class="cd-nav list-unstyled">
        <li class="cd-selected" data-menu="index">
            <a href="javsacript:void(0);">
                <span>
                    <i class="glyphicon glyphicon-home"></i>
                </span>
                <p>Dashboard</p>
            </a>
        </li>
        <li data-menu="profile">
            <a href="javsacript:void(0);">
                <span>
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                <p>Profile</p>
            </a>
        </li>
        <li data-menu="inbox">
            <a href="javsacript:void(0);">
                <span>
                    <i class="glyphicon glyphicon-envelope"></i>
                </span>
                <p>Mailbox</p>
            </a>
        </li>
        <li data-menu="#">
            <a href="javsacript:void(0);">
                <span>
                    <i class="glyphicon glyphicon-tasks"></i>
                </span>
                <p>Tasks</p>
            </a>
        </li>
        <li data-menu="#">
            <a href="javsacript:void(0);">
                <span>
                    <i class="glyphicon glyphicon-cog"></i>
                </span>
                <p>Settings</p>
            </a>
        </li>
        <li data-menu="calendar">
            <a href="javsacript:void(0);">
                <span>
                    <i class="glyphicon glyphicon-calendar"></i>
                </span>
                <p>Calendar</p>
            </a>
        </li>
    </ul>
</nav>

app/views/layouts/shared_backoffice/_search.html.erb
<form class="search-form" action="#" method="GET">
    <div class="input-group">
        <input type="text" name="search" class="form-control search-input" placeholder="Search...">
        <span class="input-group-btn">
            <button class="btn btn-default close-search waves-effect waves-button waves-classic" type="button"><i class="fa fa-times"></i></button>
        </span>
    </div><!-- Input Group -->
</form><!-- Search Form -->