config/routes.rb
Rails.application.routes.draw do

  namespace :backoffice do
    resources :gyms, except: [:show]
    resources :students, except: [:show]
    resources :roles, except: [:show]
    resources :profiles, except: [:show]
    resources :admins, except: [:show]

    get '/states/:state_id/cities', to: 'cities#cities_of_state'
  end

  devise_for :admins, :skip => [:registrations]
  root 'backoffice/gyms#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    @admin = Admin.new
    @admins = Admin.actives
    @profiles = Profile.actives
  end

  def new
    @admin = Admin.new
    @profiles = Profile.actives
    respond_to do |format|
      format.js
    end
  end

  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        flash.now[:notice] = I18n.t('messages.created_with', item: @admin.email)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.created_errors_with', item: @admin.model_name.human)
        format.js
      end
    end
  end

  def edit
    @profiles = Profile.actives
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @admin.update_attributes(admin_params)
        flash.now[:notice] = I18n.t('messages.updated_with', item: @admin.email)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.updated_errors_with', item: @admin.email)
        format.js
      end
    end
  end

  def destroy
    respond_to do |format|
      if @admin.deactivate
        flash.now[:notice] = I18n.t('messages.destroyed_with', item: @admin.email)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.destroyed_errors_with', item: @admin.email)
        format.js
      end
    end
  end

  private
    def set_admin
      @admin = Admin.find(params[:id])
    end

    def admin_params
      if password_blank? && !create_action?
        params.require(:admin).permit(:id, :email, profile_ids: [])
      else
        params.require(:admin).permit(:id, :email, :password, :password_confirmation, profile_ids: [])
      end
    end

    def admin_update_params
      params.require(:admin).permit(:id, :email, profile_ids: [])
    end

    def password_blank?
      params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
    end

    def create_action?
      params[:action] == 'create'
    end
end

app/controllers/backoffice/cities_controller.rb
class Backoffice::CitiesController < BackofficeController

  def index
    @cities = City.cities_of_state(params[:state_id])
    render json: @cities
  end

  def cities_of_state
    @cities = City.cities_of_state(params[:state_id])
    render json: @cities
  end

end

app/controllers/backoffice/gyms_controller.rb
class Backoffice::GymsController < BackofficeController
  before_action :set_gym, only: [:edit, :update, :destroy]

  def index
    @gym = Gym.new
    @gyms = Gym.descending_order(params[:page])

    if params[:query].present?
      @gyms = Gym.search(params[:query])

      respond_to do |format|
        format.js
      end
    end
  end

  def new
    @gym = Gym.new
    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @gym.update_attributes(gym_params)
        flash.now[:notice] = I18n.t('messages.updated_with', item: @gym.name)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.updated_errors_with', item: @gym.name)
        format.js
      end
    end
  end

  def create
    @gym = Gym.new(gym_params)

    respond_to do |format|
      if @gym.save
        flash.now[:notice] = I18n.t('messages.created_with', item: @gym.name)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.created_errors_with', item: @gym.model_name.human)
        format.js
      end
    end
  end

  def destroy
    respond_to do |format|
      if @gym.deactivate
        flash.now[:notice] = I18n.t('messages.destroyed_with', item: @gym.name)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.destroyed_errors_with', item: @gym.name)
        format.js
      end
    end
  end

  private
    def set_gym
      @gym = Gym.find(params[:id])
    end

    def gym_params
      params.require(:gym).permit(:id, :name)
    end
end

app/controllers/backoffice/profiles_controller.rb
class Backoffice::ProfilesController < BackofficeController
  before_action :set_profile, only: [:edit, :update, :destroy]

  def index
    @profile = Profile.new
    #@profile.build_profile_roles
    @profiles = Profile.ascending_name_order(params[:page])

    if params[:query].present?
      @profiles = Profile.search(params[:query])

      respond_to do |format|
        format.js
      end
    end
  end

  def new
    @profile = Profile.new
    #@profile.build_profile_roles
    respond_to do |format|
      format.js
    end
  end

  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        flash.now[:notice] = I18n.t('messages.created_with', item: @profile.name)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.created_errors_with', item: @profile.model_name.human)
        format.js
      end
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @profile.update_attributes(profile_params)
        flash.now[:notice] = I18n.t('messages.updated_with', item: @profile.name)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.updated_errors_with', item: @profile.name)
        format.js
      end
    end
  end

  def destroy
    respond_to do |format|
      if @profile.deactivate
        flash.now[:notice] = I18n.t('messages.destroyed_with', item: @profile.name)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.destroyed_errors_with', item: @profile.name)
        format.js
      end
    end
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:id, :name, role_ids: [], profile_roles_attributes: [:id, :name])
    end

end

app/controllers/backoffice/roles_controller.rb
class Backoffice::RolesController < BackofficeController
  before_action :set_role, only: [:edit, :update, :destroy]

  def index
    @role = Role.new
    @roles = Role.ascending_name_order(params[:page])
    puts "111111"
    if params[:query].present?
      puts "param #{params[:query]}"
      @roles = Role.search(params[:query])
      puts "2"

      respond_to do |format|
        format.js
      end
    end
  end

  def new
    @role = Role.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        flash.now[:notice] = I18n.t('messages.created_with', item: @role.name)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.created_errors_with', item: @role.model_name.human)
        format.js
      end
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @role.update_attributes(role_params)
        flash.now[:notice] = I18n.t('messages.updated_with', item: @role.name)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.updated_errors_with', item: @role.name)
        format.js
      end
    end
  end

  def destroy
    respond_to do |format|
      if @role.deactivate
        flash.now[:notice] = I18n.t('messages.destroyed_with', item: @role.name)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.destroyed_errors_with', item: @role.name)
        format.js
      end
    end
  end

  private
    def set_role
      @role = Role.find(params[:id])
    end

    def role_params
      params.require(:role).permit(:id, :name)
    end
end

app/controllers/backoffice/students_controller.rb
class Backoffice::StudentsController < BackofficeController
  before_action :set_student, only: [:edit, :update, :destroy]

  def index
    @student = Student.new
    @student.build_address
    @states = State.all
    @cities = []
    @gyms = Gym.all
    @students = Student.actives(params[:page])

    if params[:query].present?
      @students = Student.search(params[:query])

      respond_to do |format|
        format.js
      end
    end
  end

  def new
    @student = Student.new
    @student.build_address
    @states = State.all
    @cities = []
    @gyms = Gym.all
    respond_to do |format|
      format.js
    end
  end

  def edit
    @states = State.all
    @cities = City.cities_of_state(@student.address.city.state)
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @student.update_attributes(student_params)
        flash.now[:notice] = I18n.t('messages.updated_with', item: @student.full_name)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.updated_errors_with', item: @student.full_name)
        format.js
      end
    end
  end

  def destroy
    respond_to do |format|
      if @student.deactivate
        flash.now[:notice] = I18n.t('messages.destroyed_with', item: @student.full_name)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.destroyed_errors_with', item: @student.full_name)
        format.js
      end
    end
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        flash.now[:notice] = I18n.t('messages.created_with', item: @student.full_name)
        format.js
      else
        flash.now[:alert] = I18n.t('messages.created_errors_with', item: @student.full_name)
        format.js
      end
    end
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:id, :first_name, :last_name, :full_name, :birthdate, :cpf,
        :rg, :active, :email, :sex, gym_ids: [], address_attributes: [:id, :cep, :neighborhood, :number, :complement, :address,
        :reference, :city_id, :street], gym_students_attributes: [:id, :gym_id, :student_id, :registration_date,
        :active, :_destroy, gym_attributes: [:id, :name]])
    end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  layout "backoffice"
  before_action :authenticate_admin!
  # alias_method :current_user, :current_admin

  # def current_ability
  #   @current_ability ||= Ability.new(current_admin)
  # end

  def current_ability
    current_admin.ability
  end

end

app/helpers/backoffice/gyms_helper.rb
module Backoffice::GymsHelper
end

app/helpers/backoffice/students_helper.rb
module Backoffice::StudentsHelper
  OptionsForSex = Struct.new(:id, :description)

  def options_for_sex
    options = []
    options.push(OptionsForSex.new('M', 'Masculino'))
    options.push(OptionsForSex.new('F', 'Feminino'))
    options
  end
end

app/views/backoffice/admins/create.js.erb
<% unless @admin.errors.any? %>
  $('div.errors').html('');
  $('table tbody').append("<tr id='admin-row-<%= @admin.id %>'><%= j render partial: 'backoffice/admins/shared/admin_row', locals: {admin: @admin} %></tr>");
  $('#admin_name').val('').focus();
<% else %>
  $('div.errors').html('').append("<%= j render 'backoffice/admins/shared/admin_errors' %>");
<% end %>

<% if notice.present? %>
  toastr["success"]("<%= notice %>");
<% else %>
  toastr["error"]("<%= alert %>");
<% end %>

app/views/backoffice/admins/destroy.js.erb
<% if !(@admin.active?) %>
  $("#admin-row-<%= @admin.id %>").remove();

  <% if notice.present? %>
    var modal = $('#confirm_delete_modal').modal('hide');
    toastr["success"]("<%= notice %>");
  <% else %>
    var modal = $('#confirm_delete_modal').modal('hide');
    toastr["error"]("<%= alert %>");
  <% end %>
<% else %>
  alert('não foi possível remover');
<% end %>

app/views/backoffice/admins/edit.js.erb
$('#admin_form').html("<%= j render 'backoffice/admins/shared/form' %>");

app/views/backoffice/admins/index.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'backoffice/admins' %>
<% end %>

<div class="page-title">
    <h3><%= t 'labels.register', model: @admins.model_name.human %></h3>
    <div class="page-breadcrumb">
        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li><a href="#">Layouts</a></li>
            <li class="active">Blank Page</li>
        </ol>
    </div>
</div>
<div id="main-wrapper">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-white">
        <div class="panel-heading clearfix">
          <h4 class="panel-title">Pesquisar</h4>
        </div>
        <div class="panel-body">
          <%= form_tag backoffice_admins_path, method: :get, remote: true do %>
            <div class="form-group">
              <div class="input-group">
                <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Pesquisar por...", id: "admin_search" %>
                <span class="input-group-btn">
                    <%= submit_tag "Pesquisar", class: "btn btn-primary", remote: true %>
                </span>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-white">
        <div class="panel-heading clearfix">
            <h4 class="panel-title"><%= t('messages.listing', model: @admins.model_name.human(count: 2)) %></h4>
            <%= link_to new_backoffice_admin_path, { class: 'pull-right btn btn-success btn-addon m-b-sm btn-sm', 'data-toggle': "modal", 'data-target': '.bs-example-modal-lg', 'data-backdrop': 'static', 'data-keyboard': 'false', remote: true } do %>
                <i class="fa fa-plus"></i><%= t('buttons.new') %>
            <% end %>
        </div>
        <div class="panel-body">
          <div class="row">
            <% content_for :modal_lg_content do %>
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myLargeModalLabel"><%= Admin.model_name.human %></h4>
              </div>
              <div id="admin_form">
                <%= render partial: 'backoffice/admins/shared/form' %>
              </div>
            <% end %>
            <% content_for :modal_confirm_delete do %>
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Confirmação</h4>
              </div>
              <div class="modal-body">
                <%= t('messages.confirm_delete') %>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.cancel') %></button>
                  <%= link_to t('buttons.destroy'), "/backoffice/admins/pony", method: :delete, :class => 'btn btn-danger confirm-delete-button', remote: true %>
              </div>
            <% end %>
            <div class="col-md-12">
              <div class="table-responsive">
                <table class="table table-striped table-hover">
                  <thead>
                    <tr>
                      <th><%= Admin.human_attribute_name("admin.id") %></th>
                      <th><%= Admin.human_attribute_name("admin.name") %></th>
                      <th class="text-right"><%= t 'labels.action' %></th>
                    </tr>
                  </thead>
                  <tbody id="admins-table">
                    <% if @admins.blank? %>
                      <tr>
                        <td>Não há registros</td>
                      </tr>
                    <% else %>
                      <%= render partial: 'backoffice/admins/shared/admin_rows', locals: {admins: @admins} %>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 text-center">
              <%= paginate @admins, :theme => 'twitter-bootstrap-3',
                  :pagination_class => "pagination-small pagination-centered" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/admins/index.js.erb
$('table tbody').html('').append("<tr id='admin-row-<%= @admin.id %>'><%= j render :partial => 'backoffice/admins/shared/admin_rows', locals: {admins: @admins} %></tr>");

app/views/backoffice/admins/new.js.erb
$('#admin_form').html("<%= j render 'backoffice/admins/shared/form' %>");
$('#admin_name').val('').focus();

app/views/backoffice/admins/update.js.erb
<% unless @admin.errors.any? %>
  $('div.errors').html('');
  $('tr#admin-row-<%= @admin.id %>').html("<%= j render partial: 'backoffice/admins/shared/admin_row', locals: {admin: @admin} %>");
  $('#modal').modal('hide');
<% else %>
  $('div.errors').html('').append("<%= j render :partial => 'backoffice/admins/shared/admin_errors', locals: {admin: @admin} %>");
<% end %>

<% if notice.present? %>
  toastr["success"]("<%= notice %>");
<% else %>
  toastr["error"]("<%= alert %>");
<% end %>