config/routes.rb
Rails.application.routes.draw do

  namespace :backoffice do
    resources :gyms, except: [:show]
    resources :students, except: [:show]
    resources :roles, except: [:show]
    resources :profiles, except: [:show]
    resources :admins, except: [:show]

    get '/states/:state_id/cities', to: 'cities#cities_of_state'
  end

  devise_for :admins, :skip => [:registrations]
  root 'backoffice/gyms#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/role.rb
class Role < ApplicationRecord
  before_create :set_role
  before_update :set_update_role

  has_many :profile_roles
  has_many :profiles, through: :profile_roles

  # Constants
  PER_PAGE_ITEMS = 6

  # Validates
  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates_uniqueness_of :name

  # Scopes
  scope :ascending_name_order, -> (page) {
    where(active: true).order(name: :asc).page(page).per(PER_PAGE_ITEMS)
  }

  scope :search, -> (query) {
    where("name LIKE ? AND active = true", "#{query.to_s}").order(name: :asc).page(1).per(PER_PAGE_ITEMS)
  }

  def deactivate
    update(active: false)
  end

  def set_role
    self.active = true
    self.name.upcase!
  end

  def set_update_role
    self.name.upcase!
  end
end

app/views/backoffice/admins/shared/_admin_errors.html.erb
<div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><%= t 'messages.created_errors_with', item: @admin.model_name.human %></h4>
    <ul>
        <% @admin.errors.full_messages.each do |message| %>
            <li><%= message.html_safe %></li>
        <% end %>
    </ul>
</div>

app/views/backoffice/admins/shared/_admin_row.html.erb
<th scope="row"><%= admin.id %></th>
<td><%= admin.email %></td>
<td>
  <div class="text-right">
    <%= link_to edit_backoffice_admin_path(admin), { class: 'btn btn-info btn-addon btn-xs', 'data-toggle': "modal", 'data-target': ".bs-example-modal-lg", remote: true } do %>
      <i class="fa fa-edit"></i><%= I18n.t('buttons.edit') %>
    <% end %>

    <%= link_to '#', class: 'btn btn-danger btn-xs btn-addon call-confirm-delete', :data => { :id => admin.id }  do %>
      <i class="fa fa-trash"></i><%= I18n.t('buttons.destroy') %>
    <% end %>

  </div>
</td>
</div>

app/views/backoffice/admins/shared/_admin_rows.html.erb
<% admins.each do |admin| %>
  <tr id="admin-row-<%= admin.id %>">
    <%= render partial: 'backoffice/admins/shared/admin_row', locals: {admin: admin} %>
  </tr>
<% end %>

app/views/backoffice/admins/shared/_form.html.erb
<%= simple_form_for [:backoffice, @admin], remote: true, html: { multipart: true, novalidate: false } do |f| %>
    <div class="modal-body">
      <div class="errors"></div>
      <%= f.input :email, input_html: { class: 'form-control' }, required: true, autofocus: true %>
      <%= f.input :password, input_html: { class: 'form-control' }, required: @admin.id.blank? ? true : false %>
      <%= f.input :password_confirmation, input_html: { class: 'form-control' }, required: @admin.id.blank? ? true : false %>

      <%= f.input :profile_ids, collection: @profiles, as: :check_boxes, label_method: :name, value_method: :id %>
    </div>
    <div class="modal-footer">
      <%= button_tag type: :reset, class: "btn btn-default", "data-dismiss": "modal" do %>
        <%= I18n.t 'buttons.close' %>
      <% end %>
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
<% end %>